Valentina Paula Riveros Diaz
22.608.446-0


In [ ]:
rng = np.random.default_rng(seed=1221)
#Eligo un numero para definir mi semilla

In [ ]:
import numpy as np
#Importo la libreria numpy para no sobre escribir funciones

In [ ]:
#Item 1
#(1)Considere una muestra de estrellas con las siguientes luminosidades de y distancias
Luminosidad = [1.0, 2.5, 0.8, 5.0, 10.0] #Lumiosidades, en unidades de luminosidad solar
distancias= [1.0, 2.5, 0.8, 5.0, 10.0] #Distancias, en parsec

In [ ]:
#El flujo observado de una estrella puede calcularse mediante
#F =L/4πd2

In [ ]:
#(a) Convierta las listas de luminosidades y distancias en arreglos NumPy
Luminosidad_numpy = np.array(Luminosidad)
distancia_numpy = np.array(distancias)
#Se convierte la lista de luminosidad y distancias en arreglos con numpy.

In [ ]:
L_SI = Luminosidad_numpy *3.828*10**26 #convierto las luminisdades en Watts
D_SI = distancia_numpy*3.086*10**16 #Concierto las distancias en metros

In [ ]:
#(b)Calcule el flujo observado para cada estrella en Wm−2, defina una función para esto.
def flujo_observado(Luminosidad_numpy,distancia_numpy):
    F = Luminosidad_numpy/(4*np.pi*distancia_numpy**2)
    return F
#Se genera la funcion de flujo_observado para ocuparlo a lo largo del codigo.

In [ ]:
#(c)Determine el indice de la estrella presenta el mayor flujo observado
indice_max = flujo_observado(L_SI,D_SI)#Llamo a la funcion para ocuparla
np.argmax(indice_max)#Ocupo np.argamx para determinar el indice mayor de flujo

np.int64(2)

In [ ]:
#(d)Determine el indice de la presenta el menor flujo observado
indice_min = flujo_observado(L_SI,D_SI)#Llamo a la funcion para ocuparla
np.argmin(indice_min)#Ocupo np.argmin para determinar el indice minimo de flujo

np.int64(4)

In [ ]:
#(e)Calcule el flujo promedio y la mediana del flujo de la muestra
f_obs = flujo_observado(L_SI,D_SI)#LLamo la funcion
np.mean(f_obs)#Ocupo np.mean para determinar el flujo promedio

np.float64(1.8872187089138553e-08)

In [ ]:
np.median(f_obs)#Ocupo np.median para determinar la mediana del flujo

np.float64(1.2794703111280377e-08)

In [ ]:
#(f)Si el lımite de deteccion de flujo es 10−¹¹Wm−², construya una mascara booleana
#que seleccione  ́unicamente las estrellas que puedan ser detectadas
flujos = f_obs
mascara =flujos>=10**-11
mascara
#LLamo a la funcion con la variable flujos y costruyo una mascara booleana para que solo seleccione estrellas que puedan ser seleccionadas

array([ True,  True,  True,  True,  True])

In [ ]:
#(g)Muestre los  ́ındices de las estrellas detectadas
mascara_numpy = np.array(mascara)
indices_d = np.where(mascara)[0]
indices_d
#Genero una array de la mascara previa e imprimo los indices de las estrellas detectadas

array([0, 1, 2, 3, 4])

In [ ]:
#(h)Ordene las estrellas desde la de mayor flujo observado hasta la de menor flujo observado
np.argsort(-f_obs,axis=0)
#Ocupo argsort para que ordene desde el mayor flujo al menor flujo observado

array([2, 0, 1, 3, 4])

#Item 2
(2)Un tránsito ocurre cuando un planeta pasa frente a su estrella desde nuestro punto de vista,produciendo una pequeña disminución en el flujo
observado de la estrella

Genere un arreglo temporal que cubra un intervalo de diez años, compuesto por 500
mediciones equidistantes. Considere inicialmente que el flujo normalizado de la estrella
es igual a 1 en todos los tiempos. Agregue al flujo ruido gaussiano con una desviación
estándar de 0.002 y simule un tránsito entre t = 4.5 y t = 5.0 años, disminuyendo el
flujo en 0.02 durante dicho intervalo.

In [ ]:
#Genero el arreglo temporal que cubre un intervalo de diez años compuesto por 500 mediciones equidistantes
arreglo_t = np.linspace(0, 10, 500)
# Genero un arreglo de tamaño 500 lleno de 1.
flujo = np.ones(500)
#Simulo el transito entre t =4.5 y t=5 años, y utilizo una mascara para encontrar el tiempo en el intervalo
# Usamos una máscara para encontrar los tiempos dentro de ese intervalo
mascara_transito = (arreglo_t >= 4.5) & (arreglo_t <= 5.0)
flujo[mascara_transito] -= 0.02
# Disminuyo el flujo en una escala de 0.002 y tamaño 500-
flujo_disminuido = rng.normal(loc=0.0, scale=0.002, size=500)
flujo_observado = flujo + flujo_disminuido

In [ ]:
#(a)Calcule el flujo promedio de toda la curva de luz
flujo_prom = np.mean(flujo_observado)#Calculo el promedio ocupando np.mean que es la funcion de numpy para calcular el promedio

In [ ]:
#(b)Calcule la desviación estándar del flujo
flujo_std = np.std(flujo_observado)#Calculo la desviación estándar ocupando np.std que es la funcion de numpy para calcular la desviación estándar

In [ ]:
#(c)Determine el valor mínimo del flujo y su indice
flujo_min = np.min(flujo_observado)#Calculo el valor minimo ocupando np.min que es la funcion de numpy para calcular el valor minimo
idx_min = np.argmin(flujo_observado)#Y ocupo np.argmin para indicar su indice

In [ ]:
#(d)Determine el tiempo en el cual ocurre el valor mínimo del flujo
tiempo_min = arreglo_t[idx_min]#Evaluo el tiempo en la posicion del valor minimo.

In [ ]:
#(e)Seleccionar puntos que cumplan F < F_prom - 3*sigma
mascara_3sigma = flujo_observado < (flujo_prom - 3 * flujo_std)#
puntos_filtrados = flujo_observado[mascara_3sigma]
tiempos_filtrados = arreglo_t[mascara_3sigma]
#Se ocupa una mascara para identificar los puntos que cumplan con la condicion inicial

In [ ]:
#(f)Determine cuántos puntos son identificados como posibles puntos pertenecientes al tránsito
num_puntos = len(puntos_filtrados)#Ocupo la funcion len para contar la cantidad de puntos que cumplieron la cantidad inicial

In [ ]:
#(g)Estime la profundidad del tránsito mediante (Delta F = 1 - F_transit)
f_transit = np.mean(puntos_filtrados)#Calculo el promedio ocupando np.mean que es la funcion de numpy para calcular el promedio considerando f_transit como el flujo
# promedio de los puntos selecccionados
delta_f = 1 - f_transit#Calculo la diferencia entre el flujo normalizadp y el flujo promedio del transito.

In [ ]:
#(h)Estimar la razón entre el radio del planeta y el radio de la estrella (Rp/R* = sqrt(Delta F))
razon_radios = np.sqrt(delta_f)#Ocupo la formula dada en el enunciado, ocupo np.sqrt para ocupar la funcion de raiz.

In [ ]:
#(i)Compare los tiempos identificados mediante el criterio de 3σ con el intervalo utilizado originalmente para generar el tránsito
t_min_detectado = np.min(tiempos_filtrados)#Ocupo np.min para ver el valor minimo y el np.max para ver el valor maximo
t_max_detectado = np.max(tiempos_filtrados)